### ISSUE TITLE
3rd-person camera

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-3d-mannequin#3]
The Mannequin should support 3rd person gameplay, especially platform and action games to start with.

I've looked at different games, and for these, the character tends to be centered in the middle of the screen horizontally (unlike a shooter where the camera can be on one of the character's sides):

- Zelda BotW: https://www.youtube.com/watch?v=r2JtSXXY_WY
- Mario Galaxy 2: https://youtu.be/x2dR5dfiqng?t=1297
- Dark Souls 3: https://youtu.be/CPhoprLb7kM?t=731

It should support playing with a gamepad and joysticks, as well as keyboard and mouse.

**Comment by Cheeseness** [comment]
Are we feeling like target lock-on (as seen in the Dark Souls and BotW videos) is important?

The movement-experiments branch currently has basic camera movement/follow controls. I was going to look at some kind of handling for when the camera is occluded by geometry next, but I can prioritise target lock if that's mechanically important.

**Comment by NathanLovato** [comment]
No, I think that's okay, no need for lock on target.

**Comment by NathanLovato** [comment]
I just dove into the code to do some style cleanup. The camera has 2 modes: manual and auto-rotate. If we want to add mouse support at some point that'd make it 3 different modes.
The code is already not that easy to change with that single auto-rotate boolean. How about using a state machine to separate the code between different modes?

You could have a parent state with common functions, utilities e.g. to steer the camera forward when there's a zoom-in effect, and some default behavior. I think that building upon this kind of imperative code, it's just going to get harder to polish camera motion moving forward and it'll need a rewrite eventually.

**Comment by Cheeseness** [comment]
Thanks for the style update/refactoring.

I was intending to allow mouse and gamepad input to work together rather than treating them as discrete input modes, but aiming for the hookshot mechanic will probably need to be. Can look towards separating stuff out into StateMachine nodes. At this stage, I'm expecting to do plenty of rewrites :)

I'm not sure what the nested/multi-line in-line if statement (ternary expression) is accomplishing in exchange for the negative impact it has on readability.

**Comment by NathanLovato** [comment]
> I'm not sure what the nested/multi-line in-line if statement (ternary expression) is accomplishing in exchange for the negative impact it has on readability.

This bit is a detail, I just did one pass on your code, in one go. I think there's still room for improvement regarding readability in general.

Regarding readability, yeah I shouldn't put two ternaries in one assignment. For me it's easy to read, but I understand it's not that common and it might be hard to read for the majority of people.

As far as what ternaries accomplish in the general case and why I tend to use them:

1. You set the variable once and for all, instead of setting it, then mutating it, which will likely cause bugs if you introduce a setter function later for instance.
2. They force us to cover all conditional branches - you can't leave the general `else` case out. 

The idea makes sense when you apply it throughout a codebase, it saves a lot of opportunity for bugs in the long run, like combining pure functions, etc., principles/techniques from functional programming

**Comment by NathanLovato** [comment]
Sure, I shouldn't write two ternaries in a single statement in general. Again, I mostly did a pass flattening the nested if blocks. You can improve anything anytime.

**Comment by Cheeseness** [comment]
Agree, and no problem - just wanted to be sure that there wasn't a purpose that I was missing (and clarify that my concern wasn't not liking/not being familiar with ternary expressions).

Pushed up that fix and will hopefully have something to ready commit for aiming this week.

**Comment by Cheeseness** [comment]
I understand. There's a lot to weigh up when it comes to these things in general, and even more when it's code that others are intended to use/read/learn from.

Apologies for slow communication. Wheels have been turning a bit slower at this end than I'd have liked. Got a first pass on first person aiming/hookshot solution working today, but I want to tidy it a bit more before committing.

I think for the kind of gameplay we talked about, a third person aiming implementation that doesn't interrupt movement is probably going to be a better fit, but both should use most of the same code, so I don't feel like I've been wasting effort.

**Comment by Cheeseness** [comment]
Pushed up some changes earlier today that implements a state machine for camera controls and adds a first pass on the hookshot mechanic. Summarising here since the bulk of it is related to camera-relevant controls.

There are first person and third person aiming modes in the code, each with their own independent y axis inversion setting. Currently nothing transitions to the first person aiming state, and it needs some extra work for having different vertical limits, sensitivity, etc..

At the moment, toggling aim mode is bound to the Q key and gamepad left bumper, and action is bound to the E key and gamepad B. Gamepad bindings probably aren't great - happy to take suggestions on those since I'm not really a gamepad person.

Tapping action while aiming will pull you to the targeted point (if in range) via a "zip" move state, holding action will pull you to the targeted point and enter a "hang" move state that can be left by jumping or doing another hookshotty thing.

It's all still pretty rough, and I'll continue on with refining aiming controls at a slightly faster pace (assuming I don't get sick again -_- )

**Comment by NathanLovato** [comment]
Ah, I didn't realize you were working on a hook. The hook is beyond the scope of this project: the goal here is just to have the 3rd person controller - run, jump, camera controls, and related animations.

**Comment by NathanLovato** [comment]
Sorry, I hadn't realized you were working on that. You can keep the code, but no need to push the hook mechanic further. The only element left would be to be able to control the camera with the mouse, so we can show how to code cross-platform camera controls in a course/tutorial series.

**Comment by Cheeseness** [comment]
I see. We've had some kind of miscommunication somewhere - I felt like I'd previously confirmed that this was needed and signalled over a week ago that it was what I was moving onto.

I'll prioritise mouse movement and a better implementation for auto rotation moving forwards. After that's wrapped up, we should probably have a chat.

**Comment by NathanLovato** [comment]
No worries, I'm spread over several projects lately, having to worry about keeping revenue up, so I'm not alert with everyone's work. In any case, there's no problem.

The hook mechanic we briefly discussed at the start of the project is for a future course that would use this generic 3rd person character as a base. I don't remember that we discussed the design or requirements for the hook, and I didn't write an issue for it either. If we did it's my bad, I forgot.

In general, we use issues to have every task clearly outlined, and a "meta" task to have a broader view of a system or of the current progress on a job. In the case of your current job, these are the 3 issues you have on this repo.

**Comment by Cheeseness** [comment]
I pushed up changes with mouse input earlier today, along with some debug controls for toggling Y inversion/mouse capture, and removal of the temporary timer for auto rotation.

If you could give me a nudge on Discord when you're next available to chat, that'd be great.
